name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Check and download missing files
      run: ./scripts/download_missing_files.sh

    - name: Run ESLint
      run: npm run lint
      continue-on-error: true

    - name: Auto-fix ESLint errors
      run: npm run lint -- --fix
      if: failure()

    - name: Run tests
      run: npm test
